spring:
  application:
    name: pagamentos
  # Permite a exibição de erros de rota
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  h2:
    console:
      # Habilita console do h2 para visualização dos registros criados
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 20
      connection-timeout: 30000
      leak-detection-threshold: 2000
  cloud:
    # Desabilita verificação de compatibilidade do Spring Cloud com o Spring Boot
    compatibility-verifier:
      enabled: false
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 130000 # 130 segundos para cobrir os 2 minutos do mock
  output:
    ansi:
      enabled: always

clients:
  authorization:
    url: http://localhost:8080

  email:
    url: http://localhost:8080

server:
  # Usa porta 8081 pois a porta 8080 é utilizada pelo mock
  port: 8081

security:
  # Acesso aos endpoints será feito com validação do header x-api-key pois a aplicação não possui mecanismo de autenticação
  api-key: 123456

logging:
  level:
    org.tce.pagamentos: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"